name: Docker Image CI For Dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: checkout into repository
    
    - uses: docker/setup-buildx-action@v3
      name: set up docker buildx for cache
    
    # - name: Build the Docker image
    #   run: docker build -t myimg .

    - uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

    # - name: Tag Image      
    #   run: docker tag myimg:latest amoltribhuwan/angular:angular-dev

    # - name: push image
    #   run: docker push amoltribhuwan/angular:angular
    - uses: docker/build-push-action@v3
      with: 
        context: .
        push: true
        tags: amoltribhuwan/angular:angular
        cache-from: type=registry,ref=amoltribhuwan/angular:buildcache
        cache-to: type=registry,ref=amoltribhuwan/angular:buildcache

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - uses: appleboy/ssh-action@v1.0.3
  #     name: ssh into server
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       username: ${{ secrets.SSH_USERNAME }}
  #       key: ${{ secrets.SSH_PASSWORD }}
  #       port: ${{ secrets.SSH_PORT }}
  #       script: bash /home/ubuntu/docker.sh