name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t myimg .

    - uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

    - name: Tag Image      
      run: docker tag myimg amoltribhuwan/angular:latest

    - name: push image
      run: docker push amoltribhuwan/angular:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh into server
    - uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo chmod +x docker.sh
          ./docker.sh
